### ISSUE TITLE
Put back the call for paper and submission policies

### ISSUE THREAD

**Issue by tvercaut** [MIDL-Conference/midl-website-2019#5]
For historical reasons, it would be good to keep a trace of information currently listed on:
- http://2019.midl.io/call-for-papers/
- http://2019.midl.io/submissions/

**Comment by nlessmann** [comment]
These were also copied (I merged the "author instructions" and the "submissions" pages):

* https://midl2019.netlify.com/call-for-papers.html
* https://midl2019.netlify.com/author-instructions.html

But these pages are probably a bit hard to find since they are only reachable from the homepage (at the bottom, where it says "You can still find here the call for papers, ..."). This is the same on the 2018 website, which we cleaned up after the conference by removing less relevant pages from the navigation bar. We could also put links to these items back into the navigation bar, but then we should do it on both the 2018 and the 2019 sites.

**Comment by tvercaut** [comment]
Ok, thanks. Maybe for clarity the navigation can have an "archive" link leading to a simple page listing the historical pages.

**Comment by nlessmann** [comment]
Will leave it as is for now, the navigation bar is already very full on the 2019 website. But we should think of a better way to preserve these pages, we will have the same situation every year.
